### ISSUE TITLE
Added ROS Indigo Support

### ISSUE THREAD

**Issue by chriser-** [AMZ-Driverless/fssim#1]
I slightly modified the sim to work with Ubuntu 14.04 and ROS Indigo (mostly dependencies and installation instructions for gazebo 7).
The only thing not working at this moment is the track editor (as it requires Qt5), but it was not important enough for me right now to figure it out.
https://github.com/chriser-/fssim/tree/indigo
Feel free to create a new branch in your repo if you want.
Also, feel free to create issues in my fork if you are using Indigo and you have trouble installing it.

I know that probably no one is still using Indigo, but I figured I'd share it anyways.

**Comment by kabzo** [comment]
Hey, sounds good! I created a branch `indigo` so please create a Pull Request to that branch and I will give it a look.

**Comment by chriser-** [comment]
Cool stuff! Will do.

**Comment by kabzo** [comment]
Addressed in https://github.com/AMZ-Driverless/fssim/pull/2
